In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import pandas as pd
import time

BASE_URL = "https://www.fintechscotland.com/cluster/fintech-community/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

rows = []

# Main page + pages 1-17
urls = [BASE_URL] + [
    f"{BASE_URL}page/{i}/"
    for i in range(1, 18)
]

for url in urls:
    print(f"Fetching {url}")

    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    for card in soup.select("a.fintech-card"):
        href = card.get("href")
        href = urljoin(BASE_URL, href) if href else None

        h3 = card.find("h3")
        company_name = h3.get_text(strip=True) if h3 else None

        rows.append({
            "company_name": company_name,
            "href": href
        })

    time.sleep(0.5)

# Create DataFrame and remove duplicates
df = (
    pd.DataFrame(rows)
      .drop_duplicates(subset=["href"])
      .reset_index(drop=True)
)

Fetching https://www.fintechscotland.com/cluster/fintech-community/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/1/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/2/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/3/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/4/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/5/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/6/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/7/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/8/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/9/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/10/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/11/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/12/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/13/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/14/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/15/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/16/
Fetching https://www.fintechscotland.com/cluster/fintech-community/page/17/

In [ ]:
df.head()

        company_name                                               href
0            Addepar   https://www.fintechscotland.com/fintech/addepar/
1  Agentic Workflows  https://www.fintechscotland.com/fintech/agenti...
2            alessia   https://www.fintechscotland.com/fintech/alessia/
3          Appointed  https://www.fintechscotland.com/fintech/appoin...
4            Approov   https://www.fintechscotland.com/fintech/approov/

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {
    "User-Agent": "Mozilla/5.0"
}

for i, row in df.iterrows():
    print(f"{i+1}/{len(df)}: {row['company_name']}")

    response = requests.get(row["href"], headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    sidebar = soup.select_one("div.fintech-sidebar")

    if sidebar:
        items = sidebar.select("li.overview-info-item")

        for item in items:
            spans = item.find_all("span")

            if len(spans) >= 2:
                label = spans[0].get_text(strip=True)
                value = spans[1].get_text(" ", strip=True)

                # Clean label so it's a nice column name
                label = (
                    label.lower()
                         .replace(" ", "_")
                         .replace("/", "_")
                         .replace(":", "")
                )

                df.loc[i, label] = value

    time.sleep(0.5)

1/200: Addepar
2/200: Agentic Workflows
3/200: alessia
4/200: Appointed
5/200: Approov
6/200: Bankish
7/200: BehaviourAI Lab
8/200: Blockeyfi
9/200: Blocknetica
10/200: Bravura Solutions
11/200: Cherpa.AI
12/200: CienDos
13/200: Cloud Finance
14/200: Codat
15/200: CoinJar
16/200: Conduit-ucpi
17/200: CreateFuture
18/200: CreditNature
19/200: Dashly
20/200: DataVita
21/200: docStribute
22/200: Dufrain
23/200: Dwelve
24/200: EarthTrace
25/200: Ecometrica
26/200: Environment Systems
27/200: ESG Disclose
28/200: Etiq AI
29/200: Etive Technologies
30/200: Faciit
31/200: FD Intelligence
32/200: Feetr
33/200: Fenway Data Group
34/200: FINBOURNE Technology
35/200: Finwise School Ltd
36/200: Forumm
37/200: Galveston Group
38/200: Glimzer
39/200: Graphene
40/200: Green 13 Solutions
41/200: HAELO
42/200: Hazy
43/200: Inicio AI
44/200: Investment Tribe
45/200: KORE
46/200: Kutana Pay
47/200: Larimar Pay
48/200: LastingAsset
49/200: Lendinvest
50/200: Mail Metrics
51/200: Malted AI
52/200: Market Town
53/200: Maufin
54/200: Mirador
55/200: mnAI
56/200: Money Insights
57/200: Money Means Limited
58/200: MoneyHive
59/200: My Executor Box
60/200: Mydex
61/200: MyPetCard
62/200: National Support Network
63/200: Nethermind
64/200: newsGraf
65/200: Niovant
66/200: Openbook Analytics
67/200: Opmodal
68/200: PACE AP
69/200: Panta Index Technology
70/200: Profylr
71/200: PropEco
72/200: Protostars
73/200: Pulse Market
74/200: Quoin Systems
75/200: ReadBetween
76/200: Remintify
77/200: Renti Rewards
78/200: Saltare Technologies
79/200: SensFish
80/200: Simple Financial Planning
81/200: Smardaten
82/200: Snugg
83/200: Space Intelligence
84/200: Spendbase
85/200: Stableport
86/200: Struan.ai
87/200: Syngrafii
88/200: TAISK
89/200: Teradata
90/200: Terrapin
91/200: TFE Group
92/200: TidalIQ Limited
93/200: TOKENIVE LTD
94/200: TrackGenesis
95/200: TradeGaze
96/200: TreasurySpring
97/200: URCASH
98/200: Vidai UK Limited
99/200: WOW GLOBAL SOLUTIONS LTD
100/200: Zandeo
101/200: Zonal Retail Data Systems
102/200: Yakara
103/200: Xpand Access
104/200: TranSwap
105/200: Singula Decisions
106/200: Incremental
107/200: Paysend
108/200: Mosaic Software
109/200: Lupovis
110/200: GCEX
111/200: Forrit
112/200: Love Your Employees
113/200: Elcom
114/200: Digitonic
115/200: CreditSights
116/200: BiscuitTin
117/200: Ionburst
118/200: Tembo
119/200: Gigged.AI
120/200: Know-it
121/200: Optimum Finance
122/200: Workpro
123/200: Stellar Omada
124/200: BRIDGE Payment Orchestration
125/200: Sinergi
126/200: iZettle
127/200: Financial Cloud
128/200: Asura Financial Technologies
129/200: ALMIS International
130/200: Actelligent
131/200: InfinitX
132/200: AccessFintech
133/200: Predictiva
134/200: Caseblocks
135/200: GCEX
136/200: Waracle
137/200: Musemantik
138/200: Trade in space
139/200: Exizent
140/200: KAL
141/200: Clearwater Analytics
142/200: Level E Research
143/200: Coastr
144/200: Bellrock Technology
145/200: AlbaCo
146/200: iDelta
147/200: Exception
148/200: Verimatrix
149/200: MarktoMarket Valuations Limited
150/200: Moneycorp
151/200: OneBanx
152/200: Aspen
153/200: Tindeco
154/200: Cyborn
155/200: BLK Global
156/200: WhisperClaims
157/200: Proactis
158/200: CU apps
159/200: Lifeium
160/200: Legado
161/200: AlbaFX
162/200: Avaloq
163/200: Guiide
164/200: Miconex
165/200: Women’s Coin Community
166/200: Septillion Technologies
167/200: Zumo
168/200: Sonik Pocket
169/200: Advisory Direct
170/200: FreeAgent
171/200: MoneyMatix
172/200: Soar
173/200: Zortrex
174/200: The Scotcoin Project CIC
175/200: SK Chase
176/200: Origo
177/200: Modulr
178/200: Lightbox Reward
179/200: Insure Apps
180/200: Ingenico Group
181/200: Aveni
182/200: GiftRound
183/200: FNZ
184/200: Fexco
185/200: Broker Insights
186/200: ICEFLO
187/200: Aryza
188/200: atto
189/200: Float
190/200: CardSwitcher
191/200: inbest
192/200: Nucleus
193/200: Encompass
194/200: AutoRek
195/200: LendingCrowd
196/200: Broadridge
197/200: Amiqus
198/200: Previse
199/200: Siccar
200/200: ShareIn

In [ ]:
df.tail()

,company_name,href,funding_stage,trading_for,employees,sector,valuation
195,Broadridge,https://www.fintechscotland.com/fintech/broadr...,Series C,6-10 years,200-500,Institutional tool,£1bn - £5bn
196,Amiqus,https://www.fintechscotland.com/fintech/amiqus/,Series C,1-5 years,11-50,RegTech,N/A
197,Previse,https://www.fintechscotland.com/fintech/previse/,Series B,1-5 years,11-50,Payments,N/A
198,Siccar,https://www.fintechscotland.com/fintech/siccar/,Post-seed,1-5 years,11-50,Distributed Ledger,N/A
199,ShareIn,https://www.fintechscotland.com/fintech/sharein/,Post-seed,6-10 years,11-50,Investment platform,N/A

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {
    "User-Agent": "Mozilla/5.0"
}

for i, row in df.iterrows():
    print(f"{i+1}/{len(df)}: {row['company_name']}")

    response = requests.get(row["href"], headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    # ---- TAB CONTENT EXTRACTION ----
    tab_container = soup.select_one("div.fintech-tabbed-content")

    if tab_container:
        tabs = tab_container.select("div.tab-content")

        for idx, tab in enumerate(tabs, start=1):
            # extract all text inside tab (including nested divs, p, etc.)
            text = tab.get_text(separator=" ", strip=True)

            col_name = f"tab_{idx}"
            df.loc[i, col_name] = text

    time.sleep(0.5)

1/200: Addepar
2/200: Agentic Workflows
3/200: alessia
4/200: Appointed
5/200: Approov
6/200: Bankish
7/200: BehaviourAI Lab
8/200: Blockeyfi
9/200: Blocknetica
10/200: Bravura Solutions
11/200: Cherpa.AI
12/200: CienDos
13/200: Cloud Finance
14/200: Codat
15/200: CoinJar
16/200: Conduit-ucpi
17/200: CreateFuture
18/200: CreditNature
19/200: Dashly
20/200: DataVita
21/200: docStribute
22/200: Dufrain
23/200: Dwelve
24/200: EarthTrace
25/200: Ecometrica
26/200: Environment Systems
27/200: ESG Disclose
28/200: Etiq AI
29/200: Etive Technologies
30/200: Faciit
31/200: FD Intelligence
32/200: Feetr
33/200: Fenway Data Group
34/200: FINBOURNE Technology
35/200: Finwise School Ltd
36/200: Forumm
37/200: Galveston Group
38/200: Glimzer
39/200: Graphene
40/200: Green 13 Solutions
41/200: HAELO
42/200: Hazy
43/200: Inicio AI
44/200: Investment Tribe
45/200: KORE
46/200: Kutana Pay
47/200: Larimar Pay
48/200: LastingAsset
49/200: Lendinvest
50/200: Mail Metrics
51/200: Malted AI
52/200: Market Town
53/200: Maufin
54/200: Mirador
55/200: mnAI
56/200: Money Insights
57/200: Money Means Limited
58/200: MoneyHive
59/200: My Executor Box
60/200: Mydex
61/200: MyPetCard
62/200: National Support Network
63/200: Nethermind
64/200: newsGraf
65/200: Niovant
66/200: Openbook Analytics
67/200: Opmodal
68/200: PACE AP
69/200: Panta Index Technology
70/200: Profylr
71/200: PropEco
72/200: Protostars
73/200: Pulse Market
74/200: Quoin Systems
75/200: ReadBetween
76/200: Remintify
77/200: Renti Rewards
78/200: Saltare Technologies
79/200: SensFish
80/200: Simple Financial Planning
81/200: Smardaten
82/200: Snugg
83/200: Space Intelligence
84/200: Spendbase
85/200: Stableport
86/200: Struan.ai
87/200: Syngrafii
88/200: TAISK
89/200: Teradata
90/200: Terrapin
91/200: TFE Group
92/200: TidalIQ Limited
93/200: TOKENIVE LTD
94/200: TrackGenesis
95/200: TradeGaze
96/200: TreasurySpring
97/200: URCASH
98/200: Vidai UK Limited
99/200: WOW GLOBAL SOLUTIONS LTD
100/200: Zandeo
101/200: Zonal Retail Data Systems
102/200: Yakara
103/200: Xpand Access
104/200: TranSwap
105/200: Singula Decisions
106/200: Incremental
107/200: Paysend
108/200: Mosaic Software
109/200: Lupovis
110/200: GCEX
111/200: Forrit
112/200: Love Your Employees
113/200: Elcom
114/200: Digitonic
115/200: CreditSights
116/200: BiscuitTin
117/200: Ionburst
118/200: Tembo
119/200: Gigged.AI
120/200: Know-it
121/200: Optimum Finance
122/200: Workpro
123/200: Stellar Omada
124/200: BRIDGE Payment Orchestration
125/200: Sinergi
126/200: iZettle
127/200: Financial Cloud
128/200: Asura Financial Technologies
129/200: ALMIS International
130/200: Actelligent
131/200: InfinitX
132/200: AccessFintech
133/200: Predictiva
134/200: Caseblocks
135/200: GCEX
136/200: Waracle
137/200: Musemantik
138/200: Trade in space
139/200: Exizent
140/200: KAL
141/200: Clearwater Analytics
142/200: Level E Research
143/200: Coastr
144/200: Bellrock Technology
145/200: AlbaCo
146/200: iDelta
147/200: Exception
148/200: Verimatrix
149/200: MarktoMarket Valuations Limited
150/200: Moneycorp
151/200: OneBanx
152/200: Aspen
153/200: Tindeco
154/200: Cyborn
155/200: BLK Global
156/200: WhisperClaims
157/200: Proactis
158/200: CU apps
159/200: Lifeium
160/200: Legado
161/200: AlbaFX
162/200: Avaloq
163/200: Guiide
164/200: Miconex
165/200: Women’s Coin Community
166/200: Septillion Technologies
167/200: Zumo
168/200: Sonik Pocket
169/200: Advisory Direct
170/200: FreeAgent
171/200: MoneyMatix
172/200: Soar
173/200: Zortrex
174/200: The Scotcoin Project CIC
175/200: SK Chase
176/200: Origo
177/200: Modulr
178/200: Lightbox Reward
179/200: Insure Apps
180/200: Ingenico Group
181/200: Aveni
182/200: GiftRound
183/200: FNZ
184/200: Fexco
185/200: Broker Insights
186/200: ICEFLO
187/200: Aryza
188/200: atto
189/200: Float
190/200: CardSwitcher
191/200: inbest
192/200: Nucleus
193/200: Encompass
194/200: AutoRek
195/200: LendingCrowd
196/200: Broadridge
197/200: Amiqus
198/200: Previse
199/200: Siccar
200/200: ShareIn

In [ ]:
df.head()

,company_name,href,funding_stage,trading_for,employees,sector,valuation,tab_1,tab_2,tab_3,tab_4
0,Addepar,https://www.fintechscotland.com/fintech/addepar/,N/A,11-15 years,500-1000,Data/Analytics,N/A,Addepar is a global tech and data company that...,The world of finance is in the midst of a seis...,Eric Poirier Eric Poirier is the CEO of Addepa...,
1,Agentic Workflows,https://www.fintechscotland.com/fintech/agenti...,Self-funded,1-5 years,1-5,Data/Analytics,N/A,Replacing complex and cumbersome business proc...,"In February 2024, the founder, Rob Spencer, wa...",Rob Spencer Founder and CTO,
2,alessia,https://www.fintechscotland.com/fintech/alessia/,Pre-seed,1-5 years,1-5,Personal Finance,N/A,Savers hold +£400 billion GBP in cash sitting ...,Alessia was founded with a deeply personal mis...,Jose Fajardo – CEO and Founder In 2022 I moved...,
3,Appointed,https://www.fintechscotland.com/fintech/appoin...,Series A,11-15 years,11-50,Institutional tool,N/A,Appointedd is an Edinburgh based fintech that ...,Appointedd was born in 2011 when our founder a...,Leah Hutcheon – CEO and Founder Imogene Keane ...,
4,Approov,https://www.fintechscotland.com/fintech/approov/,Series B,6-10 years,11-50,RegTech,N/A,Approov is an essential component of mobile ap...,A History of Innovation Our initial technology...,Ted Miracco – CEO of Approov Ted is an experie...,NaN

In [ ]:
# rename tab_1 to overview, tab_2 story, tab_3 team
df.rename(columns={
    "tab_1": "overview",
    "tab_2": "story",
    "tab_3": "team"
}, inplace=True)

In [ ]:
# delete tab_4 col
df.drop(columns=["tab_4"], inplace=True)

In [ ]:
df.head()

,company_name,href,funding_stage,trading_for,employees,sector,valuation,overview,story,team
0,Addepar,https://www.fintechscotland.com/fintech/addepar/,N/A,11-15 years,500-1000,Data/Analytics,N/A,Addepar is a global tech and data company that...,The world of finance is in the midst of a seis...,Eric Poirier Eric Poirier is the CEO of Addepa...
1,Agentic Workflows,https://www.fintechscotland.com/fintech/agenti...,Self-funded,1-5 years,1-5,Data/Analytics,N/A,Replacing complex and cumbersome business proc...,"In February 2024, the founder, Rob Spencer, wa...",Rob Spencer Founder and CTO
2,alessia,https://www.fintechscotland.com/fintech/alessia/,Pre-seed,1-5 years,1-5,Personal Finance,N/A,Savers hold +£400 billion GBP in cash sitting ...,Alessia was founded with a deeply personal mis...,Jose Fajardo – CEO and Founder In 2022 I moved...
3,Appointed,https://www.fintechscotland.com/fintech/appoin...,Series A,11-15 years,11-50,Institutional tool,N/A,Appointedd is an Edinburgh based fintech that ...,Appointedd was born in 2011 when our founder a...,Leah Hutcheon – CEO and Founder Imogene Keane ...
4,Approov,https://www.fintechscotland.com/fintech/approov/,Series B,6-10 years,11-50,RegTech,N/A,Approov is an essential component of mobile ap...,A History of Innovation Our initial technology...,Ted Miracco – CEO of Approov Ted is an experie...

In [ ]:
df.to_csv("fintech.csv")